let data,view='dashboard';
document.addEventListener('DOMContentLoaded',()=>{const sess=requireAdmin();if(!sess)return;data=loadData();document.getElementById('logoutBtn').onclick=logout;document.querySelectorAll('.nav[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));showView('dashboard')});
function showView(v){view=v;document.querySelectorAll('.nav[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const titles={dashboard:'관리자 대시보드',members:'회원관리',fees:'회비현황',special:'특별회비현황',upload:'파일 업로드',settings:'환경설정',backup:'백업/복원'};document.getElementById('pageTitle').textContent=titles[v]||'관리자 대시보드';const renders={dashboard:renderDashboard,members:renderMembers,fees:renderFees,special:renderSpecial,upload:renderUpload,settings:renderSettings,backup:renderBackup};document.getElementById('content').innerHTML=(renders[v]||renderDashboard)();bindAfterRender(v)}
function renderDashboard(){
 const rp=sum(data,'regularPaid'),rd=sum(data,'regularDue'),sp=sum(data,'specialPaid'),sd=sum(data,'specialDue');
 return `<div class="grid grid-4"><div class="card"><span class="muted">총 회원</span><div class="kpi">${data.members.length}명</div><span class="pill info">000 제외</span></div><div class="card"><span class="muted">회원회비 납부율</span><div class="kpi">${pct(rp,rd)}%</div><small class="muted">총 내야할금액 ${won(rd)}</small></div><div class="card"><span class="muted">특별회비 납부율</span><div class="kpi">${pct(sp,sd)}%</div><small class="muted">총 내야할금액 ${won(sd)}</small></div><div class="card"><span class="muted">총 남은금액</span><div class="kpi">${won((rd-rp)+(sd-sp))}</div></div></div><div class="grid grid-2" style="margin-top:18px">${donut('회원회비',rp,rd,'#16a34a')}${donut('특별회비',sp,sd,'#2563eb')}</div><div class="card" style="margin-top:18px"><h3>회원 요약</h3>${memberTable(data.members.slice(0,12))}</div>`
}
function renderMembers(){return `<div class="card"><div class="toolbar"><input id="q" placeholder="회원번호/이름/직책 검색"><button class="btn dark" id="csvMembers">CSV 다운로드</button></div><div id="list">${memberTable(data.members)}</div></div>`}
function renderFees(){return `<div class="card"><div class="toolbar"><input id="q" placeholder="회원번호/이름 검색"><span class="pill info">월 ${won(data.settings.monthlyFee)} · 연 ${won(data.settings.monthlyFee*data.settings.annualMonths)}</span></div><div id="list">${feeTable(data.members)}</div></div>`}
function renderSpecial(){return `<div class="card"><div class="toolbar"><input id="q" placeholder="회원번호/이름 검색"><span class="pill info">경조사 1건 ${won(data.settings.specialFeePerEvent)}</span></div><div id="list">${specialTable(data.members)}</div></div>`}
function renderUpload(){return `<div class="grid grid-2"><div class="card upload-box"><h3>회원정보 업로드</h3><p class="muted">회원번호 000은 자동 제외됩니다.</p><input type="file" id="membersFile" accept=".xlsx,.xls"></div><div class="card upload-box"><h3>회비내역 업로드</h3><p class="muted">정기회비 셀에 ‘면제’, ‘면제 [회칙]’, ‘면제 [고문]’, ‘EXEMPT’가 있으면 해당 회원은 회비면제로 처리됩니다.</p><input type="file" id="feesFile" accept=".xlsx,.xls"></div><div class="card upload-box"><h3>특별회비 업로드</h3><input type="file" id="specialFile" accept=".xlsx,.xls"></div><div class="card"><h3>데이터 관리</h3><p>업로드 즉시 현재 환경설정 금액으로 다시 계산됩니다.</p><button class="btn red" id="resetData">기본값 초기화</button></div></div>`}
function renderSettings(){const s=data.settings;return `<div class="card settings-card"><h3>회비 기준 설정</h3><p class="muted">변경 후 저장하면 관리자와 모든 회원 화면의 금액·그래프가 즉시 다시 계산됩니다.</p><div class="form-grid"><label>월 회원회비<input id="monthlyFee" type="number" min="0" step="1000" value="${s.monthlyFee}"></label><label>연간 납부 개월<input id="annualMonths" type="number" min="1" max="12" value="${s.annualMonths}"></label><label>특별회비 1건당 금액<input id="specialFee" type="number" min="0" step="1000" value="${s.specialFeePerEvent}"></label></div><div class="setting-preview"><span>회원회비 연간 내야할금액</span><b id="annualPreview">${won(s.monthlyFee*s.annualMonths)}</b></div><button class="primary settings-save" id="saveSettings">설정 저장</button></div>`}
function renderBackup(){return `<div class="grid grid-2"><div class="card"><h3>JSON 백업</h3><button class="btn dark" id="backupBtn">백업 다운로드</button></div><div class="card"><h3>JSON 복원</h3><input type="file" id="restoreFile" accept=".json"></div></div>`}
function bindAfterRender(v){
 const q=document.getElementById('q');if(q)q.oninput=()=>{const term=q.value.trim(),rows=data.members.filter(m=>(m.memberNo+m.name+m.role).includes(term));document.getElementById('list').innerHTML=v==='special'?specialTable(rows):v==='fees'?feeTable(rows):memberTable(rows)};
 const csv=document.getElementById('csvMembers');if(csv)csv.onclick=()=>downloadCSV(data);
 const reset=document.getElementById('resetData');if(reset)reset.onclick=()=>{if(!confirm('업로드 및 수정 데이터를 기본값으로 초기화할까요?'))return;localStorage.removeItem(STORE_KEY);data=loadData();alert('기본값으로 초기화했습니다.');showView('dashboard')};
 const backup=document.getElementById('backupBtn');if(backup)backup.onclick=()=>downloadFile('dongwonfc_backup_v9_2.json',JSON.stringify(data,null,2),'application/json');
 const restore=document.getElementById('restoreFile');if(restore)restore.onchange=e=>readText(e.target.files[0]).then(t=>{try{data=saveData(JSON.parse(t));alert('복원 완료');showView('dashboard')}catch(err){alert('올바른 백업 파일이 아닙니다.')}});
 const mf=document.getElementById('membersFile');if(mf)mf.onchange=e=>parseWorkbook(e.target.files[0],parseMembersSheet,data,()=>{data=loadData();showView('dashboard')});
 const ff=document.getElementById('feesFile');if(ff)ff.onchange=e=>parseWorkbook(e.target.files[0],parseFeesSheet,data,()=>{data=loadData();showView('dashboard')});
 const sf=document.getElementById('specialFile');if(sf)sf.onchange=e=>parseWorkbook(e.target.files[0],parseSpecialSheet,data,()=>{data=loadData();showView('dashboard')});
 const monthly=document.getElementById('monthlyFee'),months=document.getElementById('annualMonths'),preview=document.getElementById('annualPreview');if(monthly&&months)monthly.oninput=months.oninput=()=>preview.textContent=won((+monthly.value||0)*(+months.value||0));
 const save=document.getElementById('saveSettings');if(save)save.onclick=()=>{const monthlyFee=+monthly.value,annualMonths=+months.value,specialFeePerEvent=+document.getElementById('specialFee').value;if(monthlyFee<0||annualMonths<1||annualMonths>12||specialFeePerEvent<0){alert('설정값을 확인하세요.');return}data.settings={monthlyFee,annualMonths,specialFeePerEvent};data=saveData(data);alert('회비 기준을 저장하고 전체 금액을 다시 계산했습니다.');showView('settings')};
}
