import {requireRole,logoutFirebase,db,doc,setDoc,collection,onSnapshot,writeBatch,serverTimestamp,createMemberAuth,memberEmail,sha256,getDoc} from './firebase-service.js';
import {DEFAULT_SETTINGS,visibleMembers,normalizeMember,won,pct,donut,memberTable,feeTable,specialTable,workbook,parseMembersSheet,applyFeesSheet,applySpecialSheet,esc} from './core.js';
let members=[],settings={...DEFAULT_SETTINGS},view='dashboard',unsubs=[];
document.addEventListener('DOMContentLoaded',async()=>{const session=await requireRole('admin');if(!session)return;document.getElementById('logoutBtn').onclick=logoutFirebase;document.querySelectorAll('.nav[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));subscribe();showView('dashboard')});
function subscribe(){unsubs.push(onSnapshot(doc(db,'settings','current'),s=>{settings={...DEFAULT_SETTINGS,...(s.exists()?s.data():{})};members=members.map(m=>normalizeMember(m,settings));render()}));unsubs.push(onSnapshot(collection(db,'members'),snap=>{members=visibleMembers(snap.docs.map(d=>d.data())).map(m=>normalizeMember(m,settings));render()}))}
function render(){if(document.getElementById('content'))showView(view,false)}
function showView(v,activate=true){view=v;if(activate)document.querySelectorAll('.nav[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const titles={dashboard:'관리자 대시보드',members:'회원관리',fees:'회비현황',special:'특별회비현황',upload:'파일 업로드',settings:'환경설정'};document.getElementById('pageTitle').textContent=titles[v]||titles.dashboard;const f={dashboard:dashboard,members:memberView,fees:feeView,special:specialView,upload:uploadView,settings:settingsView}[v]||dashboard;document.getElementById('content').innerHTML=f();bind(v)}
function dashboard(){const rp=members.reduce((a,m)=>a+m.regularPaid,0),rd=members.reduce((a,m)=>a+m.regularDue,0),sp=members.reduce((a,m)=>a+m.specialPaid,0),sd=members.reduce((a,m)=>a+m.specialDue,0);return`<div class="sync-note">Firebase 실시간 동기화 중입니다. 이 화면에서 수정한 내용은 다른 기기에도 즉시 반영됩니다.</div><div class="grid grid-4"><div class="card"><span class="muted">총 회원</span><div class="kpi">${members.length}명</div></div><div class="card"><span class="muted">회원회비 납부율</span><div class="kpi">${pct(rp,rd)}%</div></div><div class="card"><span class="muted">특별회비 납부율</span><div class="kpi">${pct(sp,sd)}%</div></div><div class="card"><span class="muted">총 남은금액</span><div class="kpi">${won((rd-rp)+(sd-sp))}</div></div></div><div class="grid grid-2" style="margin-top:18px">${donut('회원회비',rp,rd,'#16a34a')}${donut('특별회비',sp,sd,'#2563eb')}</div><div class="card" style="margin-top:18px"><h3>회원 요약</h3>${memberTable(members.slice(0,12))}</div>`}
function memberView(){return`<div class="card"><div class="toolbar"><input id="q" placeholder="회원번호/이름/직책 검색"><button class="btn dark" id="provisionAll">회원 로그인 계정 생성</button></div><div id="list">${memberTable(members)}</div></div>`}
function feeView(){return`<div class="card"><div class="toolbar"><input id="q" placeholder="회원번호/이름 검색"><span class="pill info">월 ${won(settings.monthlyFee)} · 연 ${won(settings.monthlyFee*settings.annualMonths)}</span></div><div id="list">${feeTable(members)}</div></div>`}
function specialView(){return`<div class="card"><div class="toolbar"><input id="q" placeholder="회원번호/이름 검색"><span class="pill info">경조사 1건 ${won(settings.specialFeePerEvent)}</span></div><div id="list">${specialTable(members)}</div></div>`}
function uploadView(){return`<div class="grid grid-2"><div class="card upload-box"><h3>회원정보 업로드</h3><p class="muted">회원번호 000은 제외됩니다. 업로드 후 ‘회원 로그인 계정 생성’을 실행하세요.</p><input type="file" id="membersFile" accept=".xlsx,.xls"></div><div class="card upload-box"><h3>회비내역 업로드</h3><p class="muted">‘면제’ 또는 ‘EXEMPT’ 표시는 회비면제로 반영됩니다.</p><input type="file" id="feesFile" accept=".xlsx,.xls"></div><div class="card upload-box"><h3>특별회비 업로드</h3><input type="file" id="specialFile" accept=".xlsx,.xls"></div><div class="card"><h3>공동 데이터 저장</h3><p>모든 업로드 자료는 Firestore에 저장되어 전체 사용자에게 실시간 반영됩니다.</p></div></div>`}
function settingsView(){return`<div class="card settings-card"><h3>회비 기준 설정</h3><div class="form-grid"><label>월 회원회비<input id="monthlyFee" type="number" value="${settings.monthlyFee}"></label><label>연간 납부 개월<input id="annualMonths" type="number" min="1" max="12" value="${settings.annualMonths}"></label><label>특별회비 1건당 금액<input id="specialFee" type="number" value="${settings.specialFeePerEvent}"></label></div><button class="primary settings-save" id="saveSettings">설정 저장</button></div>`}
function bind(v){const q=document.getElementById('q');if(q)q.oninput=()=>{const t=q.value.trim(),rows=members.filter(m=>(m.memberNo+m.name+m.role).includes(t));document.getElementById('list').innerHTML=v==='special'?specialTable(rows):v==='fees'?feeTable(rows):memberTable(rows)};document.getElementById('logoutBtn').onclick=logoutFirebase;const mf=document.getElementById('membersFile');if(mf)mf.onchange=async e=>uploadMembers(e.target.files[0]);const ff=document.getElementById('feesFile');if(ff)ff.onchange=async e=>uploadFees(e.target.files[0]);const sf=document.getElementById('specialFile');if(sf)sf.onchange=async e=>uploadSpecial(e.target.files[0]);const save=document.getElementById('saveSettings');if(save)save.onclick=saveSettings;const p=document.getElementById('provisionAll');if(p)p.onclick=provisionAll}
async function writeMembers(list){const batch=writeBatch(db);list.forEach(m=>batch.set(doc(db,'members',m.memberNo),normalizeMember(m,settings),{merge:true}));await batch.commit()}
async function uploadMembers(file){try{const wb=await workbook(file),next=parseMembersSheet(wb,members);await writeMembers(next);alert(`${next.length}명 회원정보를 공동 데이터에 저장했습니다.`)}catch(e){console.error(e);alert('회원정보 업로드 중 오류가 발생했습니다.')}}
async function uploadFees(file){try{const wb=await workbook(file),next=applyFeesSheet(wb,members);await writeMembers(next);alert('회비내역을 공동 데이터에 반영했습니다.')}catch(e){console.error(e);alert('회비내역 업로드 중 오류가 발생했습니다.')}}
async function uploadSpecial(file){try{const wb=await workbook(file),next=applySpecialSheet(wb,members);await writeMembers(next);alert('특별회비를 공동 데이터에 반영했습니다.')}catch(e){console.error(e);alert('특별회비 업로드 중 오류가 발생했습니다.')}}
async function saveSettings(){const next={monthlyFee:+document.getElementById('monthlyFee').value||0,annualMonths:+document.getElementById('annualMonths').value||12,specialFeePerEvent:+document.getElementById('specialFee').value||0,updatedAt:serverTimestamp()};await setDoc(doc(db,'settings','current'),next,{merge:true});alert('설정을 저장했습니다.')}
async function provisionAll(){if(!confirm('휴대전화 뒤 4자리를 비밀번호로 회원 Firebase 계정을 생성합니다. 진행할까요?'))return;let ok=0,skip=0,fail=0;for(const m of members){const pw=String(m.phone||'').replace(/\D/g,'').slice(-4);if(pw.length!==4){skip++;continue}try{const existing=await getDoc(doc(db,'members',m.memberNo));let uid=existing.data()?.uid;if(!uid){const user=await createMemberAuth(m,pw);uid=user.uid}await setDoc(doc(db,'users',uid),{uid,role:'member',memberNo:m.memberNo,name:m.name,email:memberEmail(m.memberNo),updatedAt:serverTimestamp()},{merge:true});await setDoc(doc(db,'members',m.memberNo),{uid},{merge:true});await setDoc(doc(db,'loginIndex',await sha256(m.name)),{email:memberEmail(m.memberNo),memberNo:m.memberNo,active:true},{merge:true});ok++}catch(e){console.warn(m.name,e);if(e.code==='auth/email-already-in-use')skip++;else fail++}}alert(`계정 처리 완료\n생성/연결: ${ok}명\n기존/건너뜀: ${skip}명\n실패: ${fail}명`)}
