import {api,requireRole,logout} from './api.js?v=11.1.0';
import {DEFAULT_SETTINGS,visibleMembers,normalizeMember,won,pct,donut,memberTable,feeTable,specialTable,workbook,parseMembersSheet,applyFeesSheet,applySpecialSheet,esc} from './core.js?v=11.1.0';
let members=[],settings={...DEFAULT_SETTINGS},auditLogs=[],view='dashboard',refreshTimer;
document.addEventListener('DOMContentLoaded',async()=>{if(!await requireRole('admin'))return;document.getElementById('logoutBtn').onclick=logout;document.querySelectorAll('.nav[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));await refresh();refreshTimer=setInterval(refresh,15000)});
async function refresh(){try{const r=await api('getAdminData');settings={...DEFAULT_SETTINGS,...r.settings};members=visibleMembers(r.members).map(m=>normalizeMember(m,settings));auditLogs=r.auditLogs||[];showView(view,false);setStatus('동기화 완료')}catch(e){setStatus(e.message,false)}}
function setStatus(t,ok=true){const el=document.getElementById('syncStatus');if(el){el.textContent=t;el.className='cloud-status '+(ok?'online':'offline')}}
function showView(v,activate=true){view=v;if(activate)document.querySelectorAll('.nav[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const titles={dashboard:'관리자 대시보드',members:'회원관리',fees:'회비현황',special:'특별회비현황',upload:'파일 업로드',settings:'환경설정',audit:'변경 이력'};document.getElementById('pageTitle').textContent=titles[v]||titles.dashboard;const f={dashboard, members:memberView,fees:feeView,special:specialView,upload:uploadView,settings:settingsView,audit:auditView}[v]||dashboard;document.getElementById('content').innerHTML=f();bind(v)}
function dashboard(){const rp=members.reduce((a,m)=>a+m.regularPaid,0),rd=members.reduce((a,m)=>a+m.regularDue,0),sp=members.reduce((a,m)=>a+m.specialPaid,0),sd=members.reduce((a,m)=>a+m.specialDue,0);return`<div class="sync-note">Google 스프레드시트 공동 데이터와 연결되어 있습니다. 약 15초마다 자동 갱신됩니다.</div><div class="grid grid-4"><div class="card"><span class="muted">총 회원</span><div class="kpi">${members.length}명</div></div><div class="card"><span class="muted">회원회비 납부율</span><div class="kpi">${pct(rp,rd)}%</div></div><div class="card"><span class="muted">특별회비 납부율</span><div class="kpi">${pct(sp,sd)}%</div></div><div class="card"><span class="muted">총 남은금액</span><div class="kpi">${won(Math.max(0,rd-rp)+Math.max(0,sd-sp))}</div></div></div><div class="grid grid-2" style="margin-top:18px">${donut('회원회비',rp,rd,'#16a34a')}${donut('특별회비',sp,sd,'#2563eb')}</div><div class="card" style="margin-top:18px"><h3>회원 요약</h3>${memberTable(members.slice(0,12))}</div>`}
function memberView(){return`<div class="card"><div class="toolbar"><input id="q" placeholder="회원번호/이름/직책 검색"><button class="btn dark" id="refreshBtn">지금 새로고침</button></div><div id="list">${memberTable(members)}</div></div>`}
function feeView(){return`<div class="card"><div class="toolbar"><input id="q" placeholder="회원번호/이름 검색"><span class="pill info">월 ${won(settings.monthlyFee)} · 연 ${won(settings.monthlyFee*settings.annualMonths)}</span></div><div id="list">${feeTable(members)}</div></div>`}
function specialView(){return`<div class="card"><div class="toolbar"><input id="q" placeholder="회원번호/이름 검색"><span class="pill info">경조사 1건 ${won(settings.specialFeePerEvent)}</span></div><div id="list">${specialTable(members)}</div></div>`}
function uploadView(){return`<div class="grid grid-2"><div class="card upload-box"><h3>회원정보 업로드</h3><p class="muted">회원번호 000과 탈퇴회원은 제외됩니다.</p><input type="file" id="membersFile" accept=".xlsx,.xls"></div><div class="card upload-box"><h3>회비내역 업로드</h3><p class="muted">면제 또는 EXEMPT 표시는 회비면제로 반영됩니다.</p><input type="file" id="feesFile" accept=".xlsx,.xls"></div><div class="card upload-box"><h3>특별회비 업로드</h3><input type="file" id="specialFile" accept=".xlsx,.xls"></div><div class="card"><h3>초기 자료 등록</h3><p>처음 설치할 때 현재 프로그램의 기본 회원·회비 자료를 Google 스프레드시트에 저장합니다.</p><button class="btn dark" id="seedBtn">기본자료 서버 등록</button><button class="btn" id="backupBtn">JSON 백업 다운로드</button></div></div>`}
function settingsView(){return`<div class="card settings-card"><h3>회비 기준 설정</h3><div class="form-grid"><label>월 회원회비<input id="monthlyFee" type="number" value="${settings.monthlyFee}"></label><label>연간 납부 개월<input id="annualMonths" type="number" min="1" max="12" value="${settings.annualMonths}"></label><label>특별회비 1건당 금액<input id="specialFee" type="number" value="${settings.specialFeePerEvent}"></label></div><button class="primary settings-save" id="saveSettings">설정 저장</button></div>`}
function auditView(){return`<div class="card"><h3>최근 변경 이력</h3><div class="table-wrap"><table><thead><tr><th>일시</th><th>작업</th><th>사용자</th><th>내용</th></tr></thead><tbody>${auditLogs.map(x=>`<tr><td>${esc(x.timestamp||'-')}</td><td>${esc(x.action||'-')}</td><td>${esc(x.actor||'-')}</td><td>${esc(x.details||'')}</td></tr>`).join('')||'<tr><td colspan="4">변경 이력이 없습니다.</td></tr>'}</tbody></table></div></div>`}
function bind(v){const q=document.getElementById('q');if(q)q.oninput=()=>{const t=q.value.trim(),rows=members.filter(m=>(m.memberNo+m.name+m.role).includes(t));document.getElementById('list').innerHTML=v==='special'?specialTable(rows):v==='fees'?feeTable(rows):memberTable(rows)};const r=document.getElementById('refreshBtn');if(r)r.onclick=refresh;const mf=document.getElementById('membersFile');if(mf)mf.onchange=e=>uploadMembers(e.target.files[0]);const ff=document.getElementById('feesFile');if(ff)ff.onchange=e=>uploadFees(e.target.files[0]);const sf=document.getElementById('specialFile');if(sf)sf.onchange=e=>uploadSpecial(e.target.files[0]);const s=document.getElementById('saveSettings');if(s)s.onclick=saveSettings;const seed=document.getElementById('seedBtn');if(seed)seed.onclick=seedDefault;const b=document.getElementById('backupBtn');if(b)b.onclick=downloadBackup}
async function saveAll(next,action,file=''){const normalized=visibleMembers(next).map(m=>normalizeMember(m,settings));await api('saveAll',{members:normalized,settings,action,details:file});members=normalized;showView(view,false)}
async function uploadMembers(file){if(!file)return;try{const wb=await workbook(file),next=parseMembersSheet(wb,members);await saveAll(next,'회원정보 업로드',file.name);alert(`${next.length}명 회원정보를 공동 스프레드시트에 저장했습니다.`)}catch(e){alert(e.message)}}
async function uploadFees(file){if(!file)return;try{const wb=await workbook(file),next=applyFeesSheet(wb,members);await saveAll(next,'회비내역 업로드',file.name);alert('회비내역을 반영했습니다.')}catch(e){alert(e.message)}}
async function uploadSpecial(file){if(!file)return;try{const wb=await workbook(file),next=applySpecialSheet(wb,members);await saveAll(next,'특별회비 업로드',file.name);alert('특별회비를 반영했습니다.')}catch(e){alert(e.message)}}
async function saveSettings(){settings={monthlyFee:+document.getElementById('monthlyFee').value||0,annualMonths:+document.getElementById('annualMonths').value||12,specialFeePerEvent:+document.getElementById('specialFee').value||0};await api('saveSettings',{settings});members=members.map(m=>normalizeMember(m,settings));alert('설정을 저장했습니다.');showView(view,false)}
async function seedDefault(){if(!confirm('현재 포함된 기본자료로 공동 스프레드시트를 초기화할까요?'))return;const data=window.DEFAULT_DATA;await api('saveAll',{members:visibleMembers(data.members).map(m=>normalizeMember(m,settings)),settings,action:'기본자료 등록',details:`${data.members.length}명`});await refresh();alert('기본자료를 저장했습니다.')}
function downloadBackup(){const blob=new Blob([JSON.stringify({version:'11.1.0',exportedAt:new Date().toISOString(),settings,members},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`dongwonfc-v11-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
