export const DEFAULT_SETTINGS={monthlyFee:20000,annualMonths:12,specialFeePerEvent:10000};
export function cleanNo(v){let s=String(v??'').trim();if(s.endsWith('.0'))s=s.slice(0,-2);return /^\d+$/.test(s)?s.padStart(3,'0'):s}
export function visibleMembers(list){return(list||[]).filter(m=>{const n=cleanNo(m.memberNo);return n&&n!=='000'&&m.name&&!String(m.role||'').includes('탈퇴')}).map(m=>({...m,memberNo:cleanNo(m.memberNo)})).sort((a,b)=>(+a.memberNo||9999)-(+b.memberNo||9999))}
export function isFeeExemptValue(v){const t=String(v??'').replace(/\s+/g,'').toLowerCase();return t.includes('면제')||t.includes('exempt')}
export function normalizeMember(m,settings=DEFAULT_SETTINGS){const regularExempt=Boolean(m.regularExempt);const regularDue=regularExempt?0:(+settings.monthlyFee||0)*(+settings.annualMonths||12);const regularPaid=regularExempt?0:Math.max(0,+m.regularPaid||0);const items=(m.specialItems||[]).map(i=>{const status=String(i.status||'-').trim()||'-',amount=+settings.specialFeePerEvent||10000,exempt=status==='본인경조사',paid=status==='납부'?amount:0;return{...i,amount,status,paid,remain:(status==='납부'||exempt)?0:amount}});const specialDue=items.filter(i=>i.status!=='본인경조사').reduce((a,i)=>a+i.amount,0),specialPaid=items.reduce((a,i)=>a+i.paid,0);return{...m,memberNo:cleanNo(m.memberNo),regularExempt,regularDue,regularPaid,regularRemain:Math.max(0,regularDue-regularPaid),specialItems:items,specialDue,specialPaid,specialRemain:Math.max(0,specialDue-specialPaid)}}
export function won(n){return(+n||0).toLocaleString('ko-KR')+'원'}
export function pct(p,d){d=+d||0;p=+p||0;return d?Math.min(100,Math.round(p/d*100)):100}
export function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
export function combinedRate(m){return pct((+m.regularPaid||0)+(+m.specialPaid||0),(+m.regularDue||0)+(+m.specialDue||0))}
export function donut(title,paid,due,color='#2563eb'){const remain=Math.max(0,(+due||0)-(+paid||0)),p=pct(paid,due);return`<div class="card"><h3>${title}</h3><div class="donut" style="--p:${p};--c:${color}" data-label="${p}%\n납부"></div><div class="money-row"><span>납부금액</span><b>${won(paid)}</b></div><div class="money-row due-row"><span>내야할금액</span><b>${won(due)}</b></div><div class="money-row"><span>남은금액</span><b>${won(remain)}</b></div></div>`}
export function memberTable(rows){return`<div class="table-wrap"><table><thead><tr><th>회원번호</th><th>성명</th><th>직책</th><th>회원회비 상태</th><th>납부금액</th><th>내야할금액</th><th>남은금액</th><th>특별회비 납부</th><th>특별회비 내야할금액</th><th>특별회비 남은금액</th><th>종합 납부율</th></tr></thead><tbody>${rows.map(m=>`<tr><td><b>${m.memberNo}</b></td><td>${esc(m.name)}</td><td>${esc(m.role)}</td><td><span class="pill ${m.regularExempt?'info':'ok'}">${m.regularExempt?'회비면제':'납부대상'}</span></td><td>${won(m.regularPaid)}</td><td><b>${m.regularExempt?'면제':won(m.regularDue)}</b></td><td>${won(m.regularRemain)}</td><td>${won(m.specialPaid)}</td><td>${won(m.specialDue)}</td><td>${won(m.specialRemain)}</td><td><span class="pill ${combinedRate(m)>=80?'ok':'warn'}">${combinedRate(m)}%</span></td></tr>`).join('')}</tbody></table></div>`}
export function feeTable(rows){return`<div class="table-wrap"><table><thead><tr><th>회원번호</th><th>성명</th><th>상태</th><th>납부금액</th><th>내야할금액</th><th>남은금액</th><th>납부율</th></tr></thead><tbody>${rows.map(m=>`<tr><td><b>${m.memberNo}</b></td><td>${esc(m.name)}</td><td><span class="pill ${m.regularExempt?'info':'ok'}">${m.regularExempt?'회비면제':'납부대상'}</span></td><td>${won(m.regularPaid)}</td><td>${m.regularExempt?'면제':won(m.regularDue)}</td><td>${won(m.regularRemain)}</td><td>${pct(m.regularPaid,m.regularDue)}%</td></tr>`).join('')}</tbody></table></div>`}
export function specialTable(rows){const events=[...new Set(rows.flatMap(m=>(m.specialItems||[]).map(i=>i.event)))];return`<div class="table-wrap"><table><thead><tr><th>회원번호</th><th>성명</th><th>납부금액</th><th>내야할금액</th><th>남은금액</th><th>납부율</th>${events.map(e=>`<th>${esc(e)}</th>`).join('')}</tr></thead><tbody>${rows.map(m=>`<tr><td><b>${m.memberNo}</b></td><td>${esc(m.name)}</td><td>${won(m.specialPaid)}</td><td>${won(m.specialDue)}</td><td>${won(m.specialRemain)}</td><td>${pct(m.specialPaid,m.specialDue)}%</td>${events.map(e=>{const i=(m.specialItems||[]).find(x=>x.event===e),s=i?i.status:'-';return`<td><span class="pill ${s==='납부'?'ok':s==='본인경조사'?'info':'bad'}">${esc(s)}</span></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`}
export function sheetRows(wb,nameLike){const name=wb.SheetNames.find(n=>n.includes(nameLike))||wb.SheetNames[0];return XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null})}
export function workbook(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=e=>{try{resolve(XLSX.read(new Uint8Array(e.target.result),{type:'array',cellDates:true}))}catch(err){reject(err)}};r.onerror=reject;r.readAsArrayBuffer(file)})}
export function parseMembersSheet(wb,old=[]){const rows=sheetRows(wb,'회원'),next=[];rows.forEach(r=>{const no=cleanNo(r[1]),role=String(r[3]||'').trim(),name=String(r[4]||'').trim(),phone=String(r[5]||'').trim(),jersey=String(r[6]||'').trim();if(!/^\d{3}$/.test(no)||!name||name.includes('성명')||no==='000'||role.includes('탈퇴'))return;const prev=old.find(m=>m.name===name||cleanNo(m.memberNo)===no)||{};next.push({...prev,memberNo:no,name,role,phone,jersey})});return visibleMembers(next)}
export function applyFeesSheet(wb,members){const rows=sheetRows(wb,'2026'),map=new Map(members.map(m=>[m.name,{...m}]));rows.forEach(r=>{const name=String(r[7]||'').trim(),m=map.get(name);if(!m)return;const c=r[8];if(isFeeExemptValue(c)){m.regularExempt=true;m.regularPaid=0}else{m.regularExempt=false;const n=Number(String(c??'').replace(/,/g,''));if(Number.isFinite(n))m.regularPaid=Math.max(0,n)}map.set(name,m)});return visibleMembers([...map.values()])}
export function applySpecialSheet(wb,members){const rows=sheetRows(wb,'특별'),events=[];(rows[3]||[]).forEach((c,i)=>{if(i>=3&&c&&c!=='납부금액')events.push(String(c))});const map=new Map(members.map(m=>[m.name,{...m}]));rows.slice(5).forEach(r=>{const name=String(r[2]||'').trim(),m=map.get(name);if(!m)return;m.specialItems=events.map((ev,idx)=>({event:ev,status:String(r[3+idx]||'미납').trim()||'미납'}));map.set(name,m)});return visibleMembers([...map.values()])}
